# Generated by Django 4.2.25 on 2025-11-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_email",
        ),
    ]
