# Generated by Django 4.2.25 on 2025-11-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.userprofile"
            ),
        ),
    ]
