# Generated by Django 4.2.25 on 2025-11-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userprofile_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_name",
        ),
    ]
